// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9JENqMhxwgOVnywU1nTN2lL5Xma4C3Q4',
    appId: '1:318254309385:web:559b3ad66c89a8c44458d8',
    messagingSenderId: '318254309385',
    projectId: 'ourstore-947a4',
    authDomain: 'ourstore-947a4.firebaseapp.com',
    storageBucket: 'ourstore-947a4.appspot.com',
    measurementId: 'G-ZGHZLSYJQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQeV9a9ATayDnvzoLEi3FaKMH68GB7gs',
    appId: '1:318254309385:android:22e87def400ce43a4458d8',
    messagingSenderId: '318254309385',
    projectId: 'ourstore-947a4',
    storageBucket: 'ourstore-947a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUVlnB-Sc4cKynSLwQWOgmtJ3kK1XeLY',
    appId: '1:318254309385:ios:bf837cb33df2a36a4458d8',
    messagingSenderId: '318254309385',
    projectId: 'ourstore-947a4',
    storageBucket: 'ourstore-947a4.appspot.com',
    iosBundleId: 'com.example.ourStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUVlnB-Sc4cKynSLwQWOgmtJ3kK1XeLY',
    appId: '1:318254309385:ios:bf837cb33df2a36a4458d8',
    messagingSenderId: '318254309385',
    projectId: 'ourstore-947a4',
    storageBucket: 'ourstore-947a4.appspot.com',
    iosBundleId: 'com.example.ourStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9JENqMhxwgOVnywU1nTN2lL5Xma4C3Q4',
    appId: '1:318254309385:web:7510a75179878fda4458d8',
    messagingSenderId: '318254309385',
    projectId: 'ourstore-947a4',
    authDomain: 'ourstore-947a4.firebaseapp.com',
    storageBucket: 'ourstore-947a4.appspot.com',
    measurementId: 'G-N3H456ZWSQ',
  );
}
